### ISSUE TITLE
TypeError: getActions() takes exactly 4 arguments (2 given)

### ISSUE THREAD

**Issue by alvinwng** [SamuelePolimi/TreasureBot#1]
I was trying this interesting project using the ds1 training and validation sets but it crashes after one iteration with the following error:

> File "TreasureBot-master/examples/lstm_example.py", line 47, in <module>
    bot.step(validation_set[i,t,:])
  File "core/bot.py", line 62, in step
    action = map(self.discretize, self.suggester.getActions(state))
TypeError: getActions() takes exactly 4 arguments (2 given)

It looks like getActions was called with just the argument `state` but 2 more are required. Not sure how I can fix it?

**Comment by Elitack** [comment]
Yeah, I met the same problem too... I wonder whether there was a solution towards it now?

**Comment by SamuelePolimi** [comment]
Hi guys thanks for your interest. I left this project for a while (I was busy). I'll work again on this project soon and I'll try to fix the error. Thanks for your adivces

**Comment by xsphere** [comment]
Nice job, thanks leckie-chn.
