### ISSUE TITLE
Fuzzy Extension

### ISSUE THREAD

**Issue by BotYue** [SamuelePolimi/TreasureBot#4]
Hi There,

Great work!
Have you tried to add the fuzzy extension to the framework, as mentioned in that paper? Will the fuzzy extension improve the performance?

Thanks
Yue

**Comment by SamuelePolimi** [comment]
Hi BotYue,

Thanks! At the moment the fuzzy extension is not provided. We would like to implement in the beginning a simple version of the mentioned paper, and to extend it only in a second phase. 

Warm regards,
Samuele
